In [7]:
import pandas as pd

pd.set_option("display.max_rows", 5)
# from learntools.core import binder; binder.bind(globals())
# from learntools.pandas.creating_reading_and_writing import *
print("Setup complete.")

Setup complete.

In [8]:
fruits = pd.DataFrame([[30, 21]], columns=["Apples", "Bananas"])

fruits

   Apples  Bananas
0      30       21

In [18]:
# Your code goes here. Create a dataframe matching the above diagram and assign it to the variable fruit_sales.
fruit_sales = pd.DataFrame(
    [[35, 21], [41, 34]],
    index=["2017 sales", "2018 sales"],
    columns=["Apples", "Bananas"],
)

fruit_sales

            Apples  Bananas
2017 sales      35       21
2018 sales      41       34

In [23]:
ingrediants = pd.Series(
    ["4 cups", "1 cup", "2 large", "1 can"],
    index=["Flour", "Milk", "Eggs", "Spam"],
    name="Dinner",
)

ingrediants

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: str

In [24]:
reviews = pd.read_csv("winemag-data_first150k.csv", index_col=0)

reviews

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
...,...,...,...,...,...,...,...,...,...,...
150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

In [25]:
animals = pd.DataFrame(
    {"Cows": [12, 20], "Goats": [22, 19]}, index=["Year 1", "Year 2"]
)
animals

        Cows  Goats
Year 1    12     22
Year 2    20     19

In [26]:
animals.to_csv(
    "cows_and_goats.csv", index=False
)  # Index False damit keine Nummerierung am anfang der Zeile