In [1]:
import pandas as pd

reviews = pd.read_csv("winemag-data-130k-v2.csv", index_col=0)
#pd.set_option("display.max_rows", 5)

print("Setup complete.")

Setup complete.

In [6]:
reviwes_written = reviews.groupby("taster_twitter_handle").size()

reviwes_written

taster_twitter_handle
@AnneInVino          3685
@JoeCz               5147
@bkfiona               27
@gordone_cellars     4177
@kerinokeefe        10776
@laurbuzz            1835
@mattkettmann        6332
@paulgwine           9532
@suskostrzewa        1085
@vboone              9537
@vossroger          25514
@wawinereport        4966
@wineschach         15134
@winewchristina         6
@worldwineguys       1005
dtype: int64

In [9]:
best_rating_per_price = reviews.groupby("price").points.max()

best_rating_per_price

price
4.0       86
5.0       87
6.0       88
7.0       91
8.0       91
          ..
1900.0    98
2000.0    97
2013.0    91
2500.0    96
3300.0    88
Name: points, Length: 390, dtype: int64

In [12]:
price_extremes = reviews.groupby(["variety"]).price.agg([min, max])

price_extremes

              min    max
variety
Abouriou     15.0   75.0
Agiorgitiko  10.0   66.0
Aglianico     6.0  180.0
Aidani       27.0   27.0
Airen         8.0   10.0
...           ...    ...
Zinfandel     5.0  100.0
Zlahtina     13.0   16.0
Zweigelt      9.0   70.0
Çalkarası    19.0   19.0
Žilavka      15.0   15.0

[707 rows x 2 columns]

In [26]:
sorted_varieties = price_extremes.sort_values(by=["min", "max"], ascending=False)

sorted_varieties

                    min    max
variety
Ramisco           495.0  495.0
Terrantez         236.0  236.0
Francisa          160.0  160.0
Rosenmuskateller  150.0  150.0
Tinta Negra Mole  112.0  112.0
...                 ...    ...
Vital               NaN    NaN
White Blend         NaN    NaN
White Port          NaN    NaN
Zelen               NaN    NaN
Zierfandler         NaN    NaN

[707 rows x 2 columns]

In [28]:
reviewer_mean_ratings = reviews.groupby(["taster_name"]).points.mean()

reviewer_mean_ratings

taster_name
Alexander Peartree    85.855422
Anna Lee C. Iijima    88.415629
Anne Krebiehl MW      90.562551
Carrie Dykes          86.395683
Christina Pickard     87.833333
Fiona Adams           86.888889
Jeff Jenssen          88.319756
Jim Gordon            88.626287
Joe Czerwinski        88.536235
Kerin O’Keefe         88.867947
Lauren Buzzeo         87.739510
Matt Kettmann         90.008686
Michael Schachner     86.907493
Mike DeSimone         89.101167
Paul Gregutt          89.082564
Roger Voss            88.708003
Sean P. Sullivan      88.755739
Susan Kostrzewa       86.609217
Virginie Boone        89.213379
Name: points, dtype: float64

In [29]:
reviewer_mean_ratings.describe()

count    19.000000
mean     88.233026
std       1.243610
min      85.855422
25%      87.323501
50%      88.536235
75%      88.975256
max      90.562551
Name: points, dtype: float64

In [32]:
country_variety_counts = reviews.groupby(["country", "variety"]).size().sort_values(ascending=False)

country_variety_counts

country  variety
US       Pinot Noir                  9885
         Cabernet Sauvignon          7315
         Chardonnay                  6801
France   Bordeaux-style Red Blend    4725
Italy    Red Blend                   3624
                                     ...
Mexico   Cinsault                       1
         Grenache                       1
         Merlot                         1
         Rosado                         1
Uruguay  White Blend                    1
Length: 1612, dtype: int64